[workspace]
members = ["commands", "pipeline", "xtask"]
# By default, compile everything except xtask, which should only be compiled
# when explicitly invoked.
default-members = ["commands", "pipeline"]

resolver = "2"
