[package]
name = "lumeo-pipeline"
version = "0.1.0"
authors = ["Zeeshan Ali <zeeshan@lumeo.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.0"
url = { version = "2.1", features = ["serde"] }
uuid = { version = "0.8", features = ["serde"] }

[dev-dependencies]
serde_json = "1.0.51"
