name: Dependencies

on:
  schedule:
    # every monday at 3AM (UTC?)
    - cron: '0 3 * * 1'
jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
